### ISSUE TITLE
Reading the Payee's Certificate from a Value Message

### ISSUE THREAD

**Issue by joshaidan** [burke/mintchip#2]
This is more of a question, but I was wondering if anyone has had any luck trying to read the payee's certificate from a value message?

I've figured out how to load the value message into a OpenSSL::ASN1 and read the important values like payee id, payer id, amount, etc. but I can't not figure out how to load the x509 certificate in order to verify the authentication of the value message's signature. 

What I'm trying to accomplish is essentially what they've done here:

http://developer.mintchipchallenge.com/devguide/developing/common/message-validation.html

**Comment by burke** [comment]
Does this help? https://github.com/xorrbit/mintchip/blob/303e13db27793a9e2c4fc8296d3eb207fc93f6b4/lib/mintchip.rb#L66-117

I'll be working on refactoring that and merging it into my repo at some point in the next few days.

**Comment by xorrbit** [comment]
Yeah I actually spent a fair amount of time trying to get the cert loaded from the value message but to no avail. They must be doing something weird as from my ASN1 dumps it _looks_ like it should load fine, but the openssl libs kept not loading the cert (I forget the exact error).

Next step imo would be to grab a cert that _can_ be loaded via ASN1 bytestream and compare the two and see where the difference is. Unfortunately I have no time this week, but next week I'll do this if it's still not solved :)

**Comment by joshaidan** [comment]
I like your comment:

``` ruby
# this turns an ugly statement like this:
# payee_id = message.value[0].value[2].value[0].value[0].value[0].value[2].value
# into a somewhat less ugly statement:
# payee_id = asn1_data_lookup(message.value, [0,2,0,0,0,2,0])
```

My code was looking exactly the same as your code, but that does seem like a cleaner solution.

Anyway, I too did have the same problem you did trying to load the x509 certificate. However, I did try extracting the code using the example PHP code, and I was able to import that .pem certificate it produced in to a ruby OpenSSL x509 certificate.  The php approach is a more direct approach I guess, it sort of finds where the certificate begins in the binary file, and then extracts it from there.  When I have time I'll try to take a closer look at what's going on in the PHP and see if I can reproduce it in Ruby.

The other concern I ran into is that I'm not entire sure if Ruby's OpenSSL x509 libraries provide the necessary functions to verify certificates and signatures, so this should be interesting.

**Comment by xorrbit** [comment]
It's a bit cleaner, but I'm no ruby wizard so maybe someone can even improve on asn1_data_lookup :)

Nice find on the php example. That should help with solving this issue.

The ruby OpenSSL libs do seem to have somwhat poor documentation. This might help with signature/certificate verification: http://stackoverflow.com/questions/1999096/digital-signature-verification-with-openssl

**Comment by joshaidan** [comment]
Since MintChip happened three years ago I figured it doesn't hurt to close this now. :)

Oh MintChip, I wonder what's the current state of it, if there will ever be a commercial implementation.
